### ISSUE TITLE
Trang Global-Portfolio

### ISSUE THREAD

**Issue by vvthinh** [easywebhub/Global-Portfolio#2]
link:https://easywebhub.github.io/Global-Portfolio/
![screencapture-easywebhub-github-io-global-portfolio-1474251325434](https://cloud.githubusercontent.com/assets/19403290/18621181/cee6a676-7e49-11e6-908d-32d4d10e1175.png)

**Comment by baotnq** [comment]
CNAME : globalportfolio.easywebhub.com

**Comment by baotnq** [comment]
xong chưa vậy?

**Comment by vvthinh** [comment]
globalportfolio.easywebhub.com

![download 2](https://cloud.githubusercontent.com/assets/19403290/18735216/6be8f4a2-80a6-11e6-83e8-5d82e8a4f0ba.png)

**Comment by baotnq** [comment]
test OK
